@startuml

class PortManager {
}

class Port {
 - code
 - port
 - continent
 - country
 - lat
 - long

}

class CargoManifest {
- containerId
- containerPos
- containerGrossWeight
}

class Containers {
- identification
- payload
- tare
- gross
- isoCode
- lenght
- width
- height
- temperature
- coordinates
}

PortManager "1" -right- "1..*"Port : > manages
Port"1" -right- "1..*"CargoManifest : > receives
CargoManifest "1" -right- "1..*"Containers : > controls




@enduml