@startuml
autonumber
hide footbox
activate SYSTEM
actor "Traffic Manager?" as TRAFFICMANAGER
participant ":System" as SYSTEM
activate TRAFFICMANAGER
TRAFFICMANAGER -> SYSTEM : Asks for pairs of ships


SYSTEM --> TRAFFICMANAGER : Informs operation success
deactivate SYSTEM

@enduml