@startuml

autonumber
'hide footbox
actor "Client" as CLIENT
participant ":WareHouseUI" as UI
participant ":WareHouseController" as CTRL
participant ":ConnectionFactory" as cf
participant ":CargoManifestStore" as cs
participant ":DatabaseConnection" as dc


CLIENT -> UI : Know the current situation of a specific container being used to transport my goods
activate UI
deactivate UI


UI --> CLIENT: Asks for containerId and the date
activate UI
deactivate UI
CLIENT -> UI: Input the data
activate UI
deactivate UI
UI -> CTRL: getResourceList(int portId, String day)
activate UI
deactivate UI
activate CTRL
deactivate CTRL

CTRL -> cf: getInstance()
activate CTRL
deactivate CTRL
activate cf
deactivate cf

cf --> CTRL: return instance
activate cf
deactivate cf
activate CTRL
deactivate CTRL

CTRL -> cf: getDatabaseConnection()
activate CTRL
deactivate CTRL
activate cf
deactivate cf

cf --> CTRL: return databaseConnection
activate cf
deactivate cf
activate CTRL
deactivate CTRL


CTRL -> cs: getResourceList(DatabaseConnection databaseConnection, int portId, String day)
activate CTRL
deactivate CTRL
activate cs
deactivate cs

cs -> dc: getConnection()
activate cs
deactivate cs
activate dc
deactivate dc

dc --> cs: return connection
activate dc
deactivate dc
activate cs
deactivate cs


cs --> CTRL: return result
activate cs
deactivate cs
activate CTRL
deactivate CTRL

CTRL --> UI: return result
activate CTRL
deactivate CTRL
activate UI
deactivate UI

UI--> CLIENT: Informs operation success
activate UI
deactivate UI

@enduml
