@startuml
autonumber
'hide footbox
actor "Traffic Manager" as TRAFFICMANAGER

participant "BuildGraphUI" as UI
participant ":CountryController" as CTRL
participant ":MatrixGraph" as matrix
participant ":Country" as country
participant ":GPS" as gps

TRAFFICMANAGER -> UI : Import data from countries, ports, borders and seadists from the database to build a freight network.
activate UI
deactivate UI

UI -> CTRL: buildGraph(int numberOfPorts)
activate UI
deactivate UI
activate CTRL
deactivate CTRL

CTRL -> matrix: addVertex(V vert)
activate CTRL
deactivate CTRL
activate matrix
deactivate matrix

CTRL -> country: getFronteiras()
activate CTRL
deactivate CTRL
activate country
deactivate country

country -> CTRL: return borders
activate country
deactivate country
activate CTRL
deactivate CTRL

CTRL -> matrix: addEdge(V vOrig, V vDest, E weight)
activate CTRL
deactivate CTRL
activate matrix
deactivate matrix

CTRL -> gps: dist = distanceBetweenCoordinates(double lat1, double lon1, double lat2, double lon2)
activate CTRL
deactivate CTRL
activate gps
deactivate gps

gps -> CTRL: return d
activate gps
deactivate gps
activate CTRL
deactivate CTRL

CTRL -> UI: return numberOfPorts
activate CTRL
deactivate CTRL
activate UI
deactivate UI

UI --> TRAFFICMANAGER: Informs operation success
activate UI
deactivate UI

@enduml
